[logger]
#    available levels: debug, info, warn, error
    level = "debug"
    file = "/tmp/calendar_scheduler.log"
    size = 500
    backups = 3
    age = 30

[storage]
implementation = "sql"
# implementation = "memory"
dsn = "pgsql://calendar:calendar@postgres:5432/calendar?sslmode=disable"

[scheduler]
remindIn = 1

[rabbitmq]
dsn = "amqp://guest:guest@rabbit:5672/"

[exchange]
name = "calendar"
kind = "topic"
durable = true
autoDeleted = false
internal = false
noWait = false

[publish]
mandatory = false
immediate = false
routingKey = "calendar.notification.info"
