version: '3.7'

networks:
  rabbit:
    driver: bridge
  postgres:
    driver: bridge
  calendar:
    driver: bridge

services:
  integration_tests:
    build: test
    command: 'true'
    environment:
      TESTS_AMQP_DSN: 'amqp://guest:guest@rabbit:5672/'
      TESTS_POSTGRES_DSN: 'host=postgres port=5432 user=calendar password=calendar dbname=calendar sslmode=disable'
      TESTS_HTTP_HOST: 'http://calendar:8080'
      WAIT_HOSTS: postgres:5432, rabbit:5672, calendar:8080
    depends_on:
      - calendar
    links:
      - calendar
      - calendar_scheduler
      - calendar_sender
    networks:
      - rabbit
      - postgres
      - calendar

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres_test
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: calendar
      POSTGRES_DB: calendar
    volumes:
      - ./migrations/20210722120225_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres

  rabbit:
    image: rabbitmq:3.7.17-management
    hostname: rabbit
    container_name: rabbit_test
    expose:
      - 15672
    restart: always
    networks:
      - rabbit

  calendar:
    build:
      context: .
      dockerfile: build/Dockerfile.calendar
      args:
        - CONFIG_FILE_NAME=calendar
    hostname: calendar
    container_name: calendar_test
    depends_on:
      - rabbit
      - postgres
    restart: on-failure
    environment:
      - WAIT_HOSTS=postgres:5432, rabbit:5672
    networks:
      - calendar
      - rabbit
      - postgres

  calendar_scheduler:
    build:
      context: .
      dockerfile: build/Dockerfile.calendar_scheduler
      args:
        - CONFIG_FILE_NAME=calendar_scheduler
    container_name: calendar_scheduler_test
    depends_on:
      - calendar
      - rabbit
      - postgres
    restart: on-failure
    environment:
      - WAIT_HOSTS=postgres:5432, rabbit:5672
    expose:
      - 7502
    networks:
      - rabbit
      - postgres

  calendar_sender:
    build:
      context: .
      dockerfile: build/Dockerfile.calendar_sender
      args:
        - CONFIG_FILE_NAME=calendar_sender
    container_name: calendar_sender_test
    depends_on:
      - calendar
      - rabbit
      - postgres
    restart: on-failure
    environment:
      - WAIT_HOSTS=postgres:5432, rabbit:5672
    expose:
      - 7503
    networks:
      - rabbit
      - postgres
